/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTypeRouteImport } from './routes/t.$type'
import { Route as ETypeSlugRouteImport } from './routes/e.$type.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTypeRoute = TTypeRouteImport.update({
  id: '/t/$type',
  path: '/t/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ETypeSlugRoute = ETypeSlugRouteImport.update({
  id: '/e/$type/$slug',
  path: '/e/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/t/$type': typeof TTypeRoute
  '/e/$type/$slug': typeof ETypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/t/$type': typeof TTypeRoute
  '/e/$type/$slug': typeof ETypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/t/$type': typeof TTypeRoute
  '/e/$type/$slug': typeof ETypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/t/$type' | '/e/$type/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/t/$type' | '/e/$type/$slug'
  id: '__root__' | '/' | '/t/$type' | '/e/$type/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TTypeRoute: typeof TTypeRoute
  ETypeSlugRoute: typeof ETypeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$type': {
      id: '/t/$type'
      path: '/t/$type'
      fullPath: '/t/$type'
      preLoaderRoute: typeof TTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$type/$slug': {
      id: '/e/$type/$slug'
      path: '/e/$type/$slug'
      fullPath: '/e/$type/$slug'
      preLoaderRoute: typeof ETypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TTypeRoute: TTypeRoute,
  ETypeSlugRoute: ETypeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
