/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TypeRouteImport } from './routes/$type'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTypeRouteImport } from './routes/t.$type'
import { Route as TypeSlugRouteImport } from './routes/$type_.$slug'
import { Route as ETypeSlugRouteImport } from './routes/e.$type.$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeRoute = TypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTypeRoute = TTypeRouteImport.update({
  id: '/t/$type',
  path: '/t/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeSlugRoute = TypeSlugRouteImport.update({
  id: '/$type_/$slug',
  path: '/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ETypeSlugRoute = ETypeSlugRouteImport.update({
  id: '/e/$type/$slug',
  path: '/e/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$type': typeof TypeRoute
  '/search': typeof SearchRoute
  '/$type/$slug': typeof TypeSlugRoute
  '/t/$type': typeof TTypeRoute
  '/e/$type/$slug': typeof ETypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$type': typeof TypeRoute
  '/search': typeof SearchRoute
  '/$type/$slug': typeof TypeSlugRoute
  '/t/$type': typeof TTypeRoute
  '/e/$type/$slug': typeof ETypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$type': typeof TypeRoute
  '/search': typeof SearchRoute
  '/$type_/$slug': typeof TypeSlugRoute
  '/t/$type': typeof TTypeRoute
  '/e/$type/$slug': typeof ETypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$type'
    | '/search'
    | '/$type/$slug'
    | '/t/$type'
    | '/e/$type/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$type'
    | '/search'
    | '/$type/$slug'
    | '/t/$type'
    | '/e/$type/$slug'
  id:
    | '__root__'
    | '/'
    | '/$type'
    | '/search'
    | '/$type_/$slug'
    | '/t/$type'
    | '/e/$type/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TypeRoute: typeof TypeRoute
  SearchRoute: typeof SearchRoute
  TypeSlugRoute: typeof TypeSlugRoute
  TTypeRoute: typeof TTypeRoute
  ETypeSlugRoute: typeof ETypeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$type': {
      id: '/$type'
      path: '/$type'
      fullPath: '/$type'
      preLoaderRoute: typeof TypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$type': {
      id: '/t/$type'
      path: '/t/$type'
      fullPath: '/t/$type'
      preLoaderRoute: typeof TTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$type_/$slug': {
      id: '/$type_/$slug'
      path: '/$type/$slug'
      fullPath: '/$type/$slug'
      preLoaderRoute: typeof TypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$type/$slug': {
      id: '/e/$type/$slug'
      path: '/e/$type/$slug'
      fullPath: '/e/$type/$slug'
      preLoaderRoute: typeof ETypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TypeRoute: TypeRoute,
  SearchRoute: SearchRoute,
  TypeSlugRoute: TypeSlugRoute,
  TTypeRoute: TTypeRoute,
  ETypeSlugRoute: ETypeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
