/**
 * Emits packages/schemas/generated/entities.ts — one Zod schema per
 * entity-type covering the full on-disk JSON shape (id, type, slug,
 * properties, relations). Plus an EntityDataMap discriminated by `type`
 * for downstream SDK / app code.
 */
import type { ValidatedCatalogue } from '../meta-validator.ts';
import { VocabPascal } from './value-type-to-zod.ts';

function entityDataIdentifier(entityTypeId: string): string {
  return `${VocabPascal(entityTypeId)}Data`;
}

function propertyEntryIdentifier(propertyId: string): string {
  return `${VocabPascal(propertyId)}Entry`;
}

function printEntitySchema(
  entityTypeId: string,
  entityType: ValidatedCatalogue['entityTypes'] extends ReadonlyMap<string, infer T> ? T
    : never,
  catalogue: ValidatedCatalogue,
): string {
  const ident = entityDataIdentifier(entityTypeId);

  const propLines: string[] = [];
  for (const declared of entityType.properties) {
    const propertyType = catalogue.propertyTypes.get(declared.id);
    if (!propertyType) continue;
    const entryIdent = propertyEntryIdentifier(declared.id);
    const inner = propertyType.historical ? `z.array(${entryIdent}).min(1)` : entryIdent;
    const wrapped = declared.required ? inner : `${inner}.optional()`;
    propLines.push(`    ${JSON.stringify(declared.id)}: ${wrapped},`);
  }

  return [
    `export const ${ident} = z.object({`,
    `  $schema: z.string().optional(),`,
    `  id: EntityId,`,
    `  type: z.literal(${JSON.stringify(entityTypeId)}),`,
    `  schema_version: z.number().int().positive(),`,
    `  slug: Slug,`,
    `  slug_history: z.array(Slug).default([]),`,
    `  canonical_name_key: I18nKey.optional(),`,
    `  properties: z.object({`,
    ...propLines,
    `  }),`,
    `  relations: z.array(RelationEntry).default([]),`,
    `}).passthrough();`,
    `export type ${ident} = z.infer<typeof ${ident}>;`,
    '',
  ].join('\n');
}

export function printEntitiesFile(catalogue: ValidatedCatalogue): string {
  const ids = [...catalogue.entityTypes.keys()].sort();

  const usedPropertyImports = new Set<string>();
  for (const id of ids) {
    const entityType = catalogue.entityTypes.get(id);
    if (!entityType) continue;
    for (const declared of entityType.properties) {
      if (catalogue.propertyTypes.has(declared.id)) {
        usedPropertyImports.add(propertyEntryIdentifier(declared.id));
      }
    }
  }

  const lines: string[] = [
    '// AUTOGENERATED by @onepiece-wiki/schema-engine — do not edit.',
    '// Source: /data/schemas/entity-types/*.json + property-types/*.json',
    '// Regenerate with: bun run schema:generate',
    '',
    "import { z } from 'zod';",
    'import {',
    '  EntityId,',
    '  EntityRef,',
    '  EpistemicStatus,',
    '  I18nKey,',
    '  Slug,',
    '  SourceRef,',
    "} from '@onepiece-wiki/schemas';",
  ];
  if (usedPropertyImports.size > 0) {
    const sorted = [...usedPropertyImports].sort();
    lines.push(
      `import {`,
      ...sorted.map((name) => `  ${name},`),
      `} from './property-values.ts';`,
    );
  }
  lines.push(
    '',
    '// Relations carry the epistemic base qualifiers (ADR-037) typed inside',
    '// `qualifiers`; relation-specific qualifiers ride the passthrough.',
    '// Per-relation qualifier shapes are otherwise looked up by',
    '// `relation.type` at the call site (a discriminated union across all',
    '// relation types blows up IDE perf for little payoff).',
    'const SourceRefOrList = z.union([SourceRef, z.array(SourceRef).min(1)]);',
    'const RelationEntry = z.object({',
    '  type: Slug,',
    '  target: EntityId,',
    '  // `.catchall` keeps the open string-index for relation-specific',
    '  // qualifiers (role, since, mastery_level, …) while typing the',
    '  // epistemic base qualifiers (ADR-037).',
    '  qualifiers: z.object({',
    '    epistemic_status: EpistemicStatus.optional(),',
    '    believed_by: z.array(EntityRef).optional(),',
    '    known_truth_by: z.array(EntityRef).optional(),',
    '    revealed_since: SourceRefOrList.optional(),',
    '  }).catchall(z.unknown()).optional(),',
    '}).passthrough();',
    '',
  );

  for (const id of ids) {
    const entityType = catalogue.entityTypes.get(id);
    if (!entityType) continue;
    lines.push(printEntitySchema(id, entityType, catalogue));
  }

  // Index by entity-type id (kebab-case keys, matches SDK's `entity.type`).
  const indexEntries = ids
    .map((id) => `  ${JSON.stringify(id)}: ${entityDataIdentifier(id)},`)
    .join('\n');
  lines.push(
    'export const EntityDataSchemas = {',
    indexEntries,
    '} as const;',
    '',
    'export type EntityTypeId = keyof typeof EntityDataSchemas;',
    'export type EntityDataMap = {',
    '  [K in EntityTypeId]: z.infer<typeof EntityDataSchemas[K]>;',
    '};',
    'export type EntityDataOf<T extends EntityTypeId> = EntityDataMap[T];',
    '',
  );

  return lines.join('\n');
}
