/**
 * Emits packages/schemas/generated/property-values.ts — one Zod schema
 * per property-type, describing a single historisable entry (the
 * exact shape of `properties[<id>][n]` in entity JSON files and of
 * `properties.value` in the SDK).
 *
 * For localizable property-types the entry holds `value_key: I18nKey`
 * (translation key resolved at render time). For others it holds
 * `value: <typed-from-value_type>`. Universal qualifiers (since, until,
 * source, epistemic_status, …) are flattened onto the entry to mirror
 * the on-disk JSON shape — they are not nested under a `qualifiers`
 * sub-object.
 */
import type { PropertyType, ValidatedCatalogue } from '../meta-validator.ts';
import { printValueTypeZod, VocabPascal } from './value-type-to-zod.ts';

function propertyEntryIdentifier(propertyId: string): string {
  return `${VocabPascal(propertyId)}Entry`;
}

function printQualifiers(property: PropertyType): string[] {
  const lines: string[] = [];
  for (const qual of property.allowed_qualifiers) {
    const expr = printValueTypeZod(qual.value_type, { enumRef: qual.enum_ref });
    const suffix = qual.required ? '' : '.optional()';
    lines.push(`  ${qual.id}: ${expr}${suffix},`);
  }
  return lines;
}

function printPropertySchema(property: PropertyType): string {
  const ident = propertyEntryIdentifier(property.id);
  const valueExpr = printValueTypeZod(property.value_type, {
    constraints: property.value_constraints,
    enumRef: property.value_constraints?.enum_ref,
  });
  const valueField = property.localizable
    ? `  value_key: I18nKey,`
    : `  value: ${valueExpr},`;
  const qualifierLines = printQualifiers(property);
  const body = [
    '  // Universal qualifiers — flattened on the entry, optional.',
    '  since: SourceRefOrList.optional(),',
    '  until: SourceRefOrList.optional(),',
    '  source: SourceRefOrList.optional(),',
    '  event: EntityRef.optional(),',
    '  epistemic_status: EpistemicStatus.optional(),',
    '  canon_scope: CanonScope.optional(),',
    '  review_status: ReviewStatus.optional(),',
    '  assisted_by: AssistedBy.optional(),',
    '  believed_by: z.array(EntityRef).optional(),',
    '  known_truth_by: z.array(EntityRef).optional(),',
    '  actual_value: z.unknown().optional(),',
    '  in_universe_date: z.string().optional(),',
    valueField,
    ...qualifierLines,
  ].join('\n');
  return [
    `export const ${ident} = z.object({`,
    body,
    `}).passthrough();`,
    `export type ${ident} = z.infer<typeof ${ident}>;`,
    '',
  ].join('\n');
}

export function printPropertyValuesFile(catalogue: ValidatedCatalogue): string {
  const ids = [...catalogue.propertyTypes.keys()].sort();

  const usedVocabImports = new Set<string>();
  for (const id of ids) {
    const property = catalogue.propertyTypes.get(id);
    if (!property) continue;
    const valueEnum = property.value_constraints?.enum_ref;
    if (
      valueEnum
      && (property.value_type === 'enum' || property.value_type === 'multi_enum')
    ) {
      usedVocabImports.add(`${VocabPascal(valueEnum)}Enum`);
    }
    for (const qual of property.allowed_qualifiers) {
      if (qual.enum_ref && (qual.value_type === 'enum' || qual.value_type === 'multi_enum')) {
        usedVocabImports.add(`${VocabPascal(qual.enum_ref)}Enum`);
      }
    }
  }

  const lines: string[] = [
    '// AUTOGENERATED by @onepiece-wiki/schema-engine — do not edit.',
    '// Source: /data/schemas/property-types/*.json',
    '// Regenerate with: bun run schema:generate',
    '',
    "import { z } from 'zod';",
    'import {',
    '  AssistedBy,',
    '  CanonScope,',
    '  EntityRef,',
    '  EpistemicStatus,',
    '  I18nKey,',
    '  IsoDate,',
    '  ReviewStatus,',
    '  SourceRef,',
    "} from '@onepiece-wiki/schemas';",
  ];
  if (usedVocabImports.size > 0) {
    const sorted = [...usedVocabImports].sort();
    lines.push(
      `import {`,
      ...sorted.map((name) => `  ${name},`),
      `} from './vocabularies.ts';`,
    );
  }
  lines.push(
    '',
    '// `since` / `until` / `source` accept a single source ref or a list',
    '// (one entry can cite manga + anime adapting the same moment). The',
    '// build pipeline normalises both forms to a set of reachable sources.',
    'const SourceRefOrList = z.union([SourceRef, z.array(SourceRef).min(1)]);',
    '',
  );

  for (const id of ids) {
    const property = catalogue.propertyTypes.get(id);
    if (!property) continue;
    lines.push(printPropertySchema(property));
  }

  // Indexed accessor: PropertyEntrySchemas['bounty'] → BountyEntry Zod schema.
  const indexEntries = ids
    .map((id) => `  ${JSON.stringify(id)}: ${propertyEntryIdentifier(id)},`)
    .join('\n');
  lines.push(
    'export const PropertyEntrySchemas = {',
    indexEntries,
    '} as const;',
    '',
    'export type PropertyTypeId = keyof typeof PropertyEntrySchemas;',
    'export type PropertyEntryOf<P extends PropertyTypeId> =',
    '  z.infer<typeof PropertyEntrySchemas[P]>;',
    '',
  );

  return lines.join('\n');
}
