/**
 * Emits packages/schemas/generated/vocabularies.ts — one Zod enum per
 * vocabulary file under /data/schemas/vocabulary, keyed by the
 * vocabulary id in PascalCase + `Enum` suffix.
 */
import type { ValidatedCatalogue } from '../meta-validator.ts';
import { VocabPascal } from './value-type-to-zod.ts';

export function printVocabulariesFile(catalogue: ValidatedCatalogue): string {
  const ids = [...catalogue.vocabularies.keys()].sort();
  const lines: string[] = [
    '// AUTOGENERATED by @onepiece-wiki/schema-engine — do not edit.',
    '// Source: /data/schemas/vocabulary/*.json',
    '// Regenerate with: bun run schema:generate',
    '',
    "import { z } from 'zod';",
    '',
  ];

  for (const id of ids) {
    const vocab = catalogue.vocabularies.get(id);
    if (!vocab) continue;
    const values = Object.keys(vocab.values).sort();
    const pascal = VocabPascal(id);
    lines.push(
      `export const ${pascal}Values = ${JSON.stringify(values)} as const;`,
      `export const ${pascal}Enum = z.enum(${pascal}Values);`,
      `export type ${pascal} = z.infer<typeof ${pascal}Enum>;`,
      '',
    );
  }

  // Indexed accessor: VocabularyValues['blood-types'] returns the readonly tuple.
  const indexEntries = ids
    .map((id) => `  ${JSON.stringify(id)}: ${VocabPascal(id)}Values,`)
    .join('\n');
  lines.push(
    'export const VocabularyValues = {',
    indexEntries,
    '} as const;',
    '',
    'export type VocabularyId = keyof typeof VocabularyValues;',
    'export type VocabularyValueOf<V extends VocabularyId> =',
    '  typeof VocabularyValues[V][number];',
    '',
  );

  return lines.join('\n');
}
