/**
 * Read-only access to the build artifact `/dist/onepiece.db` via
 * `bun:sqlite` (ADR-012 write-side driver, reused read-side because
 * the whole app runs under Bun). The database is NEVER written from
 * here — it is a disposable artifact regenerated by `bun run build:db`
 * (see /docs/BUILD_PIPELINE.md).
 *
 * Every query is a prepared statement, created once per process on
 * first use (lazy so importing this module never touches the
 * filesystem — only serving a request does). Row shapes mirror the
 * artifact schema (BUILD_PIPELINE §10), including the ADR-086
 * additions this app is built around: materialized inverse relation
 * rows (`is_inferred = 1`, per-direction `label` column) and the
 * `translations` / `narratives` tables.
 */
import { Database, type Statement } from 'bun:sqlite';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

export type TypeCountRow = {
  readonly type: string;
  readonly count: number;
};

export type EntityRow = {
  readonly id: string;
  readonly type: string;
  readonly slug: string;
  readonly canonical_name_key: string | null;
  readonly first_appearance_source: string | null;
  readonly data: Record<string, unknown>;
};

export type PropertyRow = {
  readonly property_id: string;
  readonly value: Record<string, unknown>;
  readonly since_source: string | null;
  readonly until_source: string | null;
  readonly epistemic_status: string;
  readonly event_id: string | null;
  readonly entry_index: number;
};

/**
 * One relation edge as seen FROM a given entity. Because the pipeline
 * materializes the inverse of every stored edge (ADR-086), selecting
 * on `source_entity_id` alone yields BOTH directions: stored rows
 * (`is_inferred = 0`, outgoing) and materialized inverses
 * (`is_inferred = 1`, i.e. edges whose stored direction points at this
 * entity). `label` carries the localized display label for THIS
 * direction, straight from the artifact.
 */
export type RelationRow = {
  readonly target_entity_id: string;
  readonly relation_type: string;
  readonly qualifiers: Record<string, unknown> | null;
  readonly since_source: string | null;
  readonly until_source: string | null;
  readonly epistemic_status: string;
  readonly label: Record<string, string> | null;
  readonly is_inferred: boolean;
};

function resolveDbPath(): string {
  const fromEnv = process.env['ONEPIECE_DB_PATH'];
  if (fromEnv !== undefined && fromEnv !== '') return fromEnv;
  // Walk up from this module towards the filesystem root looking for
  // `dist/onepiece.db`. In dev this module sits at `apps/web/server/`
  // (repo root is three levels up); in the nitro bundle it sits at
  // `apps/web/.output/server/…` — walking up covers both without
  // hardcoding a depth. Deployments that relocate the artifact set
  // ONEPIECE_DB_PATH instead.
  let dir = import.meta.dirname;
  for (;;) {
    const candidate = resolve(dir, 'dist', 'onepiece.db');
    if (existsSync(candidate)) return candidate;
    const parent = resolve(dir, '..');
    if (parent === dir) break;
    dir = parent;
  }
  return resolve(process.cwd(), 'dist', 'onepiece.db');
}

type Statements = {
  readonly typeCounts: Statement;
  readonly entitiesByType: Statement;
  readonly entityBySlug: Statement;
  readonly entityById: Statement;
  readonly propertiesByEntity: Statement;
  readonly relationsFrom: Statement;
  readonly translation: Statement;
  readonly narrative: Statement;
};

let statements: Statements | null = null;

function getStatements(): Statements {
  if (statements !== null) return statements;
  const path = resolveDbPath();
  if (!existsSync(path)) {
    throw new Error(
      `SQLite artifact not found at ${path}. Run \`bun run build:db\` first `
        + '(the web dev script does this automatically when the file is missing).',
    );
  }
  const db = new Database(path, { readonly: true });
  const entityColumns = 'id, type, slug, canonical_name_key, first_appearance_source, data';
  statements = {
    typeCounts: db.prepare(
      'SELECT type, COUNT(*) AS count FROM entities GROUP BY type ORDER BY type',
    ),
    entitiesByType: db.prepare(
      `SELECT ${entityColumns} FROM entities WHERE type = ? ORDER BY slug`,
    ),
    entityBySlug: db.prepare(
      `SELECT ${entityColumns} FROM entities WHERE type = ? AND slug = ?`,
    ),
    entityById: db.prepare(`SELECT ${entityColumns} FROM entities WHERE id = ?`),
    propertiesByEntity: db.prepare(
      `SELECT property_id, value, since_source, until_source, epistemic_status,
              event_id, entry_index
         FROM properties WHERE entity_id = ?
         ORDER BY property_id, entry_index`,
    ),
    relationsFrom: db.prepare(
      `SELECT target_entity_id, relation_type, qualifiers, since_source,
              until_source, epistemic_status, label, is_inferred
         FROM relations WHERE source_entity_id = ?
         ORDER BY is_inferred, relation_type`,
    ),
    translation: db.prepare('SELECT value FROM translations WHERE locale = ? AND key = ?'),
    narrative: db.prepare('SELECT markdown FROM narratives WHERE entity_id = ? AND locale = ?'),
  };
  return statements;
}

function parseJson<T>(value: unknown): T {
  return (typeof value === 'string' ? JSON.parse(value) : value) as T;
}

function toEntityRow(row: Record<string, unknown>): EntityRow {
  return {
    id: row['id'] as string,
    type: row['type'] as string,
    slug: row['slug'] as string,
    canonical_name_key: (row['canonical_name_key'] as string | null) ?? null,
    first_appearance_source: (row['first_appearance_source'] as string | null) ?? null,
    data: parseJson<Record<string, unknown>>(row['data']),
  };
}

export function listTypeCounts(): readonly TypeCountRow[] {
  return getStatements().typeCounts.all() as TypeCountRow[];
}

export function listEntitiesByType(type: string): readonly EntityRow[] {
  return (getStatements().entitiesByType.all(type) as Record<string, unknown>[]).map(toEntityRow);
}

export function getEntityBySlug(type: string, slug: string): EntityRow | null {
  const row = getStatements().entityBySlug.get(type, slug) as Record<string, unknown> | null;
  return row === null ? null : toEntityRow(row);
}

export function getEntityById(id: string): EntityRow | null {
  const row = getStatements().entityById.get(id) as Record<string, unknown> | null;
  return row === null ? null : toEntityRow(row);
}

export function listProperties(entityId: string): readonly PropertyRow[] {
  const rows = getStatements().propertiesByEntity.all(entityId) as Record<string, unknown>[];
  return rows.map((row) => ({
    property_id: row['property_id'] as string,
    value: parseJson<Record<string, unknown>>(row['value']),
    since_source: (row['since_source'] as string | null) ?? null,
    until_source: (row['until_source'] as string | null) ?? null,
    epistemic_status: row['epistemic_status'] as string,
    event_id: (row['event_id'] as string | null) ?? null,
    entry_index: row['entry_index'] as number,
  }));
}

export function listRelationsFrom(entityId: string): readonly RelationRow[] {
  const rows = getStatements().relationsFrom.all(entityId) as Record<string, unknown>[];
  return rows.map((row) => ({
    target_entity_id: row['target_entity_id'] as string,
    relation_type: row['relation_type'] as string,
    qualifiers: row['qualifiers'] === null
      ? null
      : parseJson<Record<string, unknown>>(row['qualifiers']),
    since_source: (row['since_source'] as string | null) ?? null,
    until_source: (row['until_source'] as string | null) ?? null,
    epistemic_status: row['epistemic_status'] as string,
    label: row['label'] === null ? null : parseJson<Record<string, string>>(row['label']),
    is_inferred: Number(row['is_inferred']) === 1,
  }));
}

/** Resolve one i18n key for a locale, falling back to `en`. */
export function getTranslation(locale: string, key: string): string | null {
  const stmt = getStatements().translation;
  const hit = stmt.get(locale, key) as { value: string; } | null;
  if (hit !== null) return hit.value;
  if (locale === 'en') return null;
  const en = stmt.get('en', key) as { value: string; } | null;
  return en === null ? null : en.value;
}

/** Narrative markdown for an entity, falling back to `en`. */
export function getNarrative(entityId: string, locale: string): string | null {
  const stmt = getStatements().narrative;
  const hit = stmt.get(entityId, locale) as { markdown: string; } | null;
  if (hit !== null) return hit.markdown;
  if (locale === 'en') return null;
  const en = stmt.get(entityId, 'en') as { markdown: string; } | null;
  return en === null ? null : en.markdown;
}
