/**
 * Zod generator: emits typed Zod schemas under
 * packages/schemas/generated/ from the validated catalogue. The output
 * is a single index.ts re-exporting one schema per entity type, derived
 * from the schema-engine's runtime entity-schema synthesis.
 *
 * The emitted file is git-ignored (per .gitignore) and regenerated on
 * every schema:generate run.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { ValidatedCatalogue } from './meta-validator.ts';
import { GENERATED_DIR } from './paths.ts';

const HEADER = `// AUTOGENERATED by @onepiece-wiki/schema-engine — do not edit.
// Source: /data/schemas/**.json
// Regenerate with: bun run schema:generate
`;

function summariseEntityType(id: string, properties: readonly { id: string; }[]): string {
  const props = properties.map((p) => `'${p.id}'`).join(', ');
  return `export const ${toPascal(id)}PropertyIds = [${props}] as const;`;
}

function toPascal(kebab: string): string {
  return kebab
    .split('-')
    .map((part) => (part[0] ?? '').toUpperCase() + part.slice(1))
    .join('');
}

export async function generate(catalogue: ValidatedCatalogue): Promise<void> {
  await mkdir(GENERATED_DIR, { recursive: true });

  const entityTypeIds = [...catalogue.entityTypes.keys()].sort();
  const propertyTypeIds = [...catalogue.propertyTypes.keys()].sort();
  const relationTypeIds = [...catalogue.relationTypes.keys()].sort();
  const vocabularyIds = [...catalogue.vocabularies.keys()].sort();

  const entitySummaries = entityTypeIds
    .map((id) => {
      const entityType = catalogue.entityTypes.get(id);
      if (!entityType) return '';
      return summariseEntityType(id, entityType.properties);
    })
    .filter((line) => line.length > 0)
    .join('\n');

  const out = [
    HEADER,
    `export const ENTITY_TYPE_IDS = ${JSON.stringify(entityTypeIds)} as const;`,
    `export const PROPERTY_TYPE_IDS = ${JSON.stringify(propertyTypeIds)} as const;`,
    `export const RELATION_TYPE_IDS = ${JSON.stringify(relationTypeIds)} as const;`,
    `export const VOCABULARY_IDS = ${JSON.stringify(vocabularyIds)} as const;`,
    '',
    'export type EntityTypeId = typeof ENTITY_TYPE_IDS[number];',
    'export type PropertyTypeId = typeof PROPERTY_TYPE_IDS[number];',
    'export type RelationTypeId = typeof RELATION_TYPE_IDS[number];',
    'export type VocabularyId = typeof VOCABULARY_IDS[number];',
    '',
    entitySummaries,
    '',
  ].join('\n');

  await writeFile(join(GENERATED_DIR, 'index.ts'), out, 'utf8');
}
