/**
 * Zod generator: emits typed Zod schemas under
 * packages/schemas/generated/ from the validated catalogue.
 *
 * Output files (all git-ignored, regenerated on every schema:generate):
 *
 *  - index.ts             ID arrays + Pascal-cased PropertyIds tuples
 *                         per entity type. Type-only consumers can stay
 *                         on this file without pulling in Zod.
 *  - vocabularies.ts      One Zod enum per /data/schemas/vocabulary file.
 *  - property-values.ts   One Zod schema per property-type covering a
 *                         single historisable entry (matches SDK
 *                         PropertyRecord.value).
 *  - entities.ts          One Zod schema per entity-type covering the
 *                         full on-disk JSON (matches SDK
 *                         EntityRecord.data) + EntityDataMap.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { ValidatedCatalogue } from './meta-validator.ts';
import { GENERATED_DIR } from './paths.ts';
import { printEntitiesFile } from './printers/entities.ts';
import { printPropertyValuesFile } from './printers/property-values.ts';
import { printVocabulariesFile } from './printers/vocabularies.ts';

const HEADER = `// AUTOGENERATED by @onepiece-wiki/schema-engine — do not edit.
// Source: /data/schemas/**.json
// Regenerate with: bun run schema:generate
`;

function summariseEntityType(id: string, properties: readonly { id: string; }[]): string {
  const props = properties.map((p) => `'${p.id}'`).join(', ');
  return `export const ${toPascal(id)}PropertyIds = [${props}] as const;`;
}

function toPascal(kebab: string): string {
  return kebab
    .split('-')
    .map((part) => (part[0] ?? '').toUpperCase() + part.slice(1))
    .join('');
}

function printIndexFile(catalogue: ValidatedCatalogue): string {
  const entityTypeIds = [...catalogue.entityTypes.keys()].sort();
  const propertyTypeIds = [...catalogue.propertyTypes.keys()].sort();
  const relationTypeIds = [...catalogue.relationTypes.keys()].sort();
  const vocabularyIds = [...catalogue.vocabularies.keys()].sort();

  const entitySummaries = entityTypeIds
    .map((id) => {
      const entityType = catalogue.entityTypes.get(id);
      if (!entityType) return '';
      return summariseEntityType(id, entityType.properties);
    })
    .filter((line) => line.length > 0)
    .join('\n');

  return [
    HEADER,
    `export const ENTITY_TYPE_IDS = ${JSON.stringify(entityTypeIds)} as const;`,
    `export const PROPERTY_TYPE_IDS = ${JSON.stringify(propertyTypeIds)} as const;`,
    `export const RELATION_TYPE_IDS = ${JSON.stringify(relationTypeIds)} as const;`,
    `export const VOCABULARY_IDS = ${JSON.stringify(vocabularyIds)} as const;`,
    '',
    '// RelationTypeId is declared here because the per-relation Zod',
    '// schemas are deferred to Phase B (see ADR-024). EntityTypeId,',
    '// PropertyTypeId, and VocabularyId are re-exported from the schema',
    '// files below — they are the canonical sources.',
    'export type RelationTypeId = typeof RELATION_TYPE_IDS[number];',
    '',
    entitySummaries,
    '',
    "export * from './vocabularies.ts';",
    "export * from './property-values.ts';",
    "export { EntityDataSchemas } from './entities.ts';",
    "export type { EntityTypeId, EntityDataMap, EntityDataOf } from './entities.ts';",
    '',
  ].join('\n');
}

export async function generate(catalogue: ValidatedCatalogue): Promise<void> {
  await mkdir(GENERATED_DIR, { recursive: true });

  await Promise.all([
    writeFile(join(GENERATED_DIR, 'vocabularies.ts'), printVocabulariesFile(catalogue), 'utf8'),
    writeFile(
      join(GENERATED_DIR, 'property-values.ts'),
      printPropertyValuesFile(catalogue),
      'utf8',
    ),
    writeFile(join(GENERATED_DIR, 'entities.ts'), printEntitiesFile(catalogue), 'utf8'),
    writeFile(join(GENERATED_DIR, 'index.ts'), printIndexFile(catalogue), 'utf8'),
  ]);
}
