/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypesTypeRouteImport } from './routes/types.$type'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as TypesTypeIndexRouteImport } from './routes/types.$type.index'
import { Route as TypesTypeTableRouteImport } from './routes/types.$type.table'
import { Route as TypesTypeNewRouteImport } from './routes/types.$type.new'
import { Route as TypesTypeSlugRouteImport } from './routes/types.$type.$slug'
import { Route as SourcesTypeSlugRouteImport } from './routes/sources.$type.$slug'
import { Route as TypesTypeSlugIndexRouteImport } from './routes/types.$type.$slug.index'
import { Route as TypesTypeSlugHistoryRouteImport } from './routes/types.$type.$slug.history'
import { Route as TypesTypeSlugApparitionsRouteImport } from './routes/types.$type.$slug.apparitions'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesTypeRoute = TypesTypeRouteImport.update({
  id: '/types/$type',
  path: '/types/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/admin/queue',
  path: '/admin/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesTypeIndexRoute = TypesTypeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TypesTypeRoute,
} as any)
const TypesTypeTableRoute = TypesTypeTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => TypesTypeRoute,
} as any)
const TypesTypeNewRoute = TypesTypeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TypesTypeRoute,
} as any)
const TypesTypeSlugRoute = TypesTypeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TypesTypeRoute,
} as any)
const SourcesTypeSlugRoute = SourcesTypeSlugRouteImport.update({
  id: '/sources/$type/$slug',
  path: '/sources/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesTypeSlugIndexRoute = TypesTypeSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TypesTypeSlugRoute,
} as any)
const TypesTypeSlugHistoryRoute = TypesTypeSlugHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => TypesTypeSlugRoute,
} as any)
const TypesTypeSlugApparitionsRoute =
  TypesTypeSlugApparitionsRouteImport.update({
    id: '/apparitions',
    path: '/apparitions',
    getParentRoute: () => TypesTypeSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/admin/queue': typeof AdminQueueRoute
  '/api/$': typeof ApiSplatRoute
  '/types/$type': typeof TypesTypeRouteWithChildren
  '/sources/$type/$slug': typeof SourcesTypeSlugRoute
  '/types/$type/$slug': typeof TypesTypeSlugRouteWithChildren
  '/types/$type/new': typeof TypesTypeNewRoute
  '/types/$type/table': typeof TypesTypeTableRoute
  '/types/$type/': typeof TypesTypeIndexRoute
  '/types/$type/$slug/apparitions': typeof TypesTypeSlugApparitionsRoute
  '/types/$type/$slug/history': typeof TypesTypeSlugHistoryRoute
  '/types/$type/$slug/': typeof TypesTypeSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/admin/queue': typeof AdminQueueRoute
  '/api/$': typeof ApiSplatRoute
  '/sources/$type/$slug': typeof SourcesTypeSlugRoute
  '/types/$type/new': typeof TypesTypeNewRoute
  '/types/$type/table': typeof TypesTypeTableRoute
  '/types/$type': typeof TypesTypeIndexRoute
  '/types/$type/$slug/apparitions': typeof TypesTypeSlugApparitionsRoute
  '/types/$type/$slug/history': typeof TypesTypeSlugHistoryRoute
  '/types/$type/$slug': typeof TypesTypeSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/admin/queue': typeof AdminQueueRoute
  '/api/$': typeof ApiSplatRoute
  '/types/$type': typeof TypesTypeRouteWithChildren
  '/sources/$type/$slug': typeof SourcesTypeSlugRoute
  '/types/$type/$slug': typeof TypesTypeSlugRouteWithChildren
  '/types/$type/new': typeof TypesTypeNewRoute
  '/types/$type/table': typeof TypesTypeTableRoute
  '/types/$type/': typeof TypesTypeIndexRoute
  '/types/$type/$slug/apparitions': typeof TypesTypeSlugApparitionsRoute
  '/types/$type/$slug/history': typeof TypesTypeSlugHistoryRoute
  '/types/$type/$slug/': typeof TypesTypeSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/login'
    | '/admin/queue'
    | '/api/$'
    | '/types/$type'
    | '/sources/$type/$slug'
    | '/types/$type/$slug'
    | '/types/$type/new'
    | '/types/$type/table'
    | '/types/$type/'
    | '/types/$type/$slug/apparitions'
    | '/types/$type/$slug/history'
    | '/types/$type/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/login'
    | '/admin/queue'
    | '/api/$'
    | '/sources/$type/$slug'
    | '/types/$type/new'
    | '/types/$type/table'
    | '/types/$type'
    | '/types/$type/$slug/apparitions'
    | '/types/$type/$slug/history'
    | '/types/$type/$slug'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/login'
    | '/admin/queue'
    | '/api/$'
    | '/types/$type'
    | '/sources/$type/$slug'
    | '/types/$type/$slug'
    | '/types/$type/new'
    | '/types/$type/table'
    | '/types/$type/'
    | '/types/$type/$slug/apparitions'
    | '/types/$type/$slug/history'
    | '/types/$type/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  AdminQueueRoute: typeof AdminQueueRoute
  ApiSplatRoute: typeof ApiSplatRoute
  TypesTypeRoute: typeof TypesTypeRouteWithChildren
  SourcesTypeSlugRoute: typeof SourcesTypeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/$type': {
      id: '/types/$type'
      path: '/types/$type'
      fullPath: '/types/$type'
      preLoaderRoute: typeof TypesTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/admin/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/$type/': {
      id: '/types/$type/'
      path: '/'
      fullPath: '/types/$type/'
      preLoaderRoute: typeof TypesTypeIndexRouteImport
      parentRoute: typeof TypesTypeRoute
    }
    '/types/$type/table': {
      id: '/types/$type/table'
      path: '/table'
      fullPath: '/types/$type/table'
      preLoaderRoute: typeof TypesTypeTableRouteImport
      parentRoute: typeof TypesTypeRoute
    }
    '/types/$type/new': {
      id: '/types/$type/new'
      path: '/new'
      fullPath: '/types/$type/new'
      preLoaderRoute: typeof TypesTypeNewRouteImport
      parentRoute: typeof TypesTypeRoute
    }
    '/types/$type/$slug': {
      id: '/types/$type/$slug'
      path: '/$slug'
      fullPath: '/types/$type/$slug'
      preLoaderRoute: typeof TypesTypeSlugRouteImport
      parentRoute: typeof TypesTypeRoute
    }
    '/sources/$type/$slug': {
      id: '/sources/$type/$slug'
      path: '/sources/$type/$slug'
      fullPath: '/sources/$type/$slug'
      preLoaderRoute: typeof SourcesTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/$type/$slug/': {
      id: '/types/$type/$slug/'
      path: '/'
      fullPath: '/types/$type/$slug/'
      preLoaderRoute: typeof TypesTypeSlugIndexRouteImport
      parentRoute: typeof TypesTypeSlugRoute
    }
    '/types/$type/$slug/history': {
      id: '/types/$type/$slug/history'
      path: '/history'
      fullPath: '/types/$type/$slug/history'
      preLoaderRoute: typeof TypesTypeSlugHistoryRouteImport
      parentRoute: typeof TypesTypeSlugRoute
    }
    '/types/$type/$slug/apparitions': {
      id: '/types/$type/$slug/apparitions'
      path: '/apparitions'
      fullPath: '/types/$type/$slug/apparitions'
      preLoaderRoute: typeof TypesTypeSlugApparitionsRouteImport
      parentRoute: typeof TypesTypeSlugRoute
    }
  }
}

interface TypesTypeSlugRouteChildren {
  TypesTypeSlugApparitionsRoute: typeof TypesTypeSlugApparitionsRoute
  TypesTypeSlugHistoryRoute: typeof TypesTypeSlugHistoryRoute
  TypesTypeSlugIndexRoute: typeof TypesTypeSlugIndexRoute
}

const TypesTypeSlugRouteChildren: TypesTypeSlugRouteChildren = {
  TypesTypeSlugApparitionsRoute: TypesTypeSlugApparitionsRoute,
  TypesTypeSlugHistoryRoute: TypesTypeSlugHistoryRoute,
  TypesTypeSlugIndexRoute: TypesTypeSlugIndexRoute,
}

const TypesTypeSlugRouteWithChildren = TypesTypeSlugRoute._addFileChildren(
  TypesTypeSlugRouteChildren,
)

interface TypesTypeRouteChildren {
  TypesTypeSlugRoute: typeof TypesTypeSlugRouteWithChildren
  TypesTypeNewRoute: typeof TypesTypeNewRoute
  TypesTypeTableRoute: typeof TypesTypeTableRoute
  TypesTypeIndexRoute: typeof TypesTypeIndexRoute
}

const TypesTypeRouteChildren: TypesTypeRouteChildren = {
  TypesTypeSlugRoute: TypesTypeSlugRouteWithChildren,
  TypesTypeNewRoute: TypesTypeNewRoute,
  TypesTypeTableRoute: TypesTypeTableRoute,
  TypesTypeIndexRoute: TypesTypeIndexRoute,
}

const TypesTypeRouteWithChildren = TypesTypeRoute._addFileChildren(
  TypesTypeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  AdminQueueRoute: AdminQueueRoute,
  ApiSplatRoute: ApiSplatRoute,
  TypesTypeRoute: TypesTypeRouteWithChildren,
  SourcesTypeSlugRoute: SourcesTypeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
