/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypesTypeRouteImport } from './routes/types.$type'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as TypesTypeTableRouteImport } from './routes/types.$type.table'
import { Route as TypesTypeSlugRouteImport } from './routes/types.$type.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesTypeRoute = TypesTypeRouteImport.update({
  id: '/types/$type',
  path: '/types/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesTypeTableRoute = TypesTypeTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => TypesTypeRoute,
} as any)
const TypesTypeSlugRoute = TypesTypeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TypesTypeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/types/$type': typeof TypesTypeRouteWithChildren
  '/types/$type/$slug': typeof TypesTypeSlugRoute
  '/types/$type/table': typeof TypesTypeTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/types/$type': typeof TypesTypeRouteWithChildren
  '/types/$type/$slug': typeof TypesTypeSlugRoute
  '/types/$type/table': typeof TypesTypeTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/types/$type': typeof TypesTypeRouteWithChildren
  '/types/$type/$slug': typeof TypesTypeSlugRoute
  '/types/$type/table': typeof TypesTypeTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/$'
    | '/types/$type'
    | '/types/$type/$slug'
    | '/types/$type/table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/$'
    | '/types/$type'
    | '/types/$type/$slug'
    | '/types/$type/table'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/$'
    | '/types/$type'
    | '/types/$type/$slug'
    | '/types/$type/table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  TypesTypeRoute: typeof TypesTypeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/$type': {
      id: '/types/$type'
      path: '/types/$type'
      fullPath: '/types/$type'
      preLoaderRoute: typeof TypesTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/$type/table': {
      id: '/types/$type/table'
      path: '/table'
      fullPath: '/types/$type/table'
      preLoaderRoute: typeof TypesTypeTableRouteImport
      parentRoute: typeof TypesTypeRoute
    }
    '/types/$type/$slug': {
      id: '/types/$type/$slug'
      path: '/$slug'
      fullPath: '/types/$type/$slug'
      preLoaderRoute: typeof TypesTypeSlugRouteImport
      parentRoute: typeof TypesTypeRoute
    }
  }
}

interface TypesTypeRouteChildren {
  TypesTypeSlugRoute: typeof TypesTypeSlugRoute
  TypesTypeTableRoute: typeof TypesTypeTableRoute
}

const TypesTypeRouteChildren: TypesTypeRouteChildren = {
  TypesTypeSlugRoute: TypesTypeSlugRoute,
  TypesTypeTableRoute: TypesTypeTableRoute,
}

const TypesTypeRouteWithChildren = TypesTypeRoute._addFileChildren(
  TypesTypeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  TypesTypeRoute: TypesTypeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
